// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationDALLibrary.Contexts;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotificationDALLibrary.Migrations
{
    [DbContext(typeof(NotificationContext))]
    partial class NotificationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotificationModelLibrary.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PK_Notification");

                    b.HasIndex("UserEmail");

                    b.ToTable("Notifications");

                    b.HasDiscriminator<string>("NotificationType").HasValue("Notification");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("NotificationModelLibrary.Models.User", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Email")
                        .HasName("PK_User");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Email = "siva@gmail.com",
                            Name = "siva",
                            PhoneNumber = "9787899545"
                        });
                });

            modelBuilder.Entity("NotificationModelLibrary.Models.EmailNotification", b =>
                {
                    b.HasBaseType("NotificationModelLibrary.Models.Notification");

                    b.Property<string>("ToEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("email");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Message = "Welcome to our service!",
                            SentDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserEmail = "siva@gmail.com",
                            ToEmail = "siva@gmail.com"
                        });
                });

            modelBuilder.Entity("NotificationModelLibrary.Models.SmsNotification", b =>
                {
                    b.HasBaseType("NotificationModelLibrary.Models.Notification");

                    b.Property<string>("ToPhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("sms");
                });

            modelBuilder.Entity("NotificationModelLibrary.Models.Notification", b =>
                {
                    b.HasOne("NotificationModelLibrary.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NotificationModelLibrary.Models.User", b =>
                {
                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
